#!/usr/bin/env bash
# install.sh — Install the clone-website skill for multiple AI coding agents.
#
# Usage:
#   bash install.sh                    # Install for all detected platforms
#   bash install.sh --claude           # Claude Code only
#   bash install.sh --all              # All platforms
#   bash install.sh --project <dir>    # Install project-level rules into <dir>
#
# Supported platforms:
#   Claude Code, Codex CLI, Cursor, Windsurf, Cline, Aider,
#   GitHub Copilot, Roo Code, Continue, Kiro, Trae, Amazon Q, Augment Code

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Helpers ─────────────────────────────────────────────────────────────

green()  { printf '\033[0;32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$1"; }
red()    { printf '\033[0;31m%s\033[0m\n' "$1"; }

copy_skill_dir() {
  local dest="$1"
  mkdir -p "$dest"
  cp -r "$SKILL_DIR"/* "$dest/"
  green "  ✓ Installed to $dest"
}

# Generate a condensed instruction file for non-Claude agents
generate_agent_rules() {
  local dest_file="$1"
  local platform_name="$2"
  mkdir -p "$(dirname "$dest_file")"

  cat > "$dest_file" <<'RULES_EOF'
# AI Website Cloner — Agent Instructions

> AUTO-GENERATED by clone-website skill installer.
> Source: clone-website/SKILL.md

## Overview

Reverse-engineer any website and rebuild it as a pixel-perfect clone using
Next.js 16 (App Router), React 19, Tailwind CSS v4 (oklch tokens), shadcn/ui,
and TypeScript strict.

## Tech Stack

| Layer       | Choice                                              |
|-------------|-----------------------------------------------------|
| Framework   | Next.js 16 — App Router, React 19, TypeScript strict|
| Styling     | Tailwind CSS v4 — oklch design tokens               |
| Components  | shadcn/ui (Radix primitives + Tailwind)             |
| Icons       | Lucide React (replaced by extracted SVGs)           |
| Pkg manager | npm                                                 |

## Coding Standards

1. TypeScript strict — no `any`, no `@ts-ignore`
2. Server Components by default — only `"use client"` with hooks/events/browser APIs
3. One component per file — filename matches default export
4. Tailwind only — no inline `style` unless computed CSS requires it
5. oklch colors via CSS custom properties in globals.css (never hex/rgb)
6. Semantic HTML — `<header>`, `<nav>`, `<main>`, `<section>`, `<footer>`
7. Accessible — alt text, labels, WCAG AA contrast
8. No dead code
9. Commit often — conventional commit messages

## Clone Pipeline (5 Phases)

### Phase 1 — Reconnaissance
- Screenshot at 1440px, 768px, 375px → `docs/design-references/`
- Extract design tokens → `docs/research/design-tokens.json`
- Capture interaction states → `docs/research/interactions.md`
- Inventory sections → `docs/research/section-inventory.md`

### Phase 2 — Foundation
- Convert colors to oklch in `src/app/globals.css`
- Configure fonts via `next/font/google` or `@font-face`
- Download assets → `public/images/`, `public/videos/`, `public/seo/`
- Extract SVG icons → `src/components/icons.tsx`
- Update metadata in `src/app/layout.tsx`

### Phase 3 — Component Specs
- One spec per section in `docs/research/components/<name>.md`
- Include: layout, typography, colors, spacing, interactions, responsive, content, assets

### Phase 4 — Build
- One component file per spec: `src/components/<Name>.tsx`
- Use only Tailwind classes + oklch CSS vars
- Local asset paths only (no external URLs)
- Assemble in `src/app/page.tsx`

### Phase 5 — QA
- `npm run build` — zero errors
- Screenshot at all breakpoints, visual diff against Phase 1
- `npm run lint` — zero warnings
- Fix all discrepancies

## Project Structure

```
src/app/              # Routes + globals.css
src/components/       # Section components + ui/ primitives
src/lib/utils.ts      # cn() utility
src/types/            # Shared interfaces
src/hooks/            # Custom hooks
public/images|videos|seo/  # Downloaded assets
docs/research/components/  # Per-component specs
docs/design-references/    # Screenshots
```

## Commands

```bash
npm run dev    # localhost:3000
npm run build  # Production build
npm run lint   # Lint check
```
RULES_EOF

  green "  ✓ $dest_file ($platform_name)"
}

# ── Installation targets ────────────────────────────────────────────────

install_claude() {
  local claude_dir="$HOME/.claude/skills/clone-website"
  copy_skill_dir "$claude_dir"
  green "  → Claude Code: Use /clone-website <url>"
}

install_project_rules() {
  local project_dir="${1:-.}"

  # Platform-specific rule files (project level)
  declare -A FLAT_TARGETS=(
    [".cursorrules"]="Cursor IDE"
    [".windsurfrules"]="Windsurf IDE"
    [".clinerules"]="Cline"
    [".aider.conf.md"]="Aider"
    ["codex.md"]="Codex CLI"
  )

  declare -A NESTED_TARGETS=(
    [".github/copilot-instructions.md"]="GitHub Copilot"
    [".roo/rules.md"]="Roo Code"
    [".continue/config.md"]="Continue"
    [".kiro/rules.md"]="Kiro"
    [".trae/rules.md"]="Trae"
    [".amazonq/rules.md"]="Amazon Q"
    [".augment/rules.md"]="Augment Code"
  )

  echo ""
  echo "Installing project-level agent rules into: $project_dir"

  for target in "${!FLAT_TARGETS[@]}"; do
    generate_agent_rules "$project_dir/$target" "${FLAT_TARGETS[$target]}"
  done

  for target in "${!NESTED_TARGETS[@]}"; do
    generate_agent_rules "$project_dir/$target" "${NESTED_TARGETS[$target]}"
  done
}

# ── CLI ─────────────────────────────────────────────────────────────────

show_help() {
  cat <<EOF
clone-website skill installer

Usage:
  bash install.sh                     Install Claude Code skill (global)
  bash install.sh --all               Claude + all project-level rules in cwd
  bash install.sh --claude            Claude Code only
  bash install.sh --project <dir>     Project-level rules for all agents in <dir>
  bash install.sh --help              Show this help

Platforms: Claude Code, Codex, Cursor, Windsurf, Cline, Aider,
           Copilot, Roo, Continue, Kiro, Trae, Amazon Q, Augment
EOF
}

case "${1:-}" in
  --help|-h)
    show_help
    ;;
  --claude)
    echo "Installing for Claude Code..."
    install_claude
    ;;
  --project)
    install_project_rules "${2:-.}"
    ;;
  --all)
    echo "Installing for all platforms..."
    install_claude
    install_project_rules "."
    ;;
  *)
    echo "Installing for Claude Code (default)..."
    install_claude
    echo ""
    yellow "Tip: Use --all to also generate project-level rules for other agents."
    yellow "     Use --project <dir> to install into a specific project."
    ;;
esac

echo ""
green "Done!"
